// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeKeyword(arg1:string):Promise<main.KeywordAnalysisResult>;

export function CollectCreatorAdvisor(arg1:string):Promise<main.CreatorAdvisorResponse>;

export function GetConfig():Promise<main.Config>;

export function GetSearchAdLog():Promise<string>;

export function GetUsage():Promise<main.Usage>;

export function RunAutoExtract(arg1:Record<string, any>):Promise<Array<main.AutoExtractResult>>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetZoom(arg1:number):Promise<number>;

export function TestSearchAd():Promise<main.SearchAdTestResult>;
