// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeKeyword(arg1) {
  return window['go']['main']['App']['AnalyzeKeyword'](arg1);
}

export function CollectCreatorAdvisor(arg1) {
  return window['go']['main']['App']['CollectCreatorAdvisor'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSearchAdLog() {
  return window['go']['main']['App']['GetSearchAdLog']();
}

export function GetUsage() {
  return window['go']['main']['App']['GetUsage']();
}

export function RunAutoExtract(arg1) {
  return window['go']['main']['App']['RunAutoExtract'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetZoom(arg1) {
  return window['go']['main']['App']['SetZoom'](arg1);
}

export function TestSearchAd() {
  return window['go']['main']['App']['TestSearchAd']();
}
